-- EXPLORATORY DATA ANALYSIS

SELECT *
FROM layoffs_staging2;

SELECT MAX(total_laid_off), MAX(percentage_laid_off)
FROM layoffs_staging2;

-- CHECKING COMPANIES THAT CEASED OPERATIONS
SELECT *
FROM layoffs_staging2
WHERE percentage_laid_off = 1
ORDER BY total_laid_off DESC;


-- CHECKING TOTAL LAID OFF BY A COMPANY IN MULTIPLE INSTANCES IN THE SCOPE OF DATASET
SELECT company, SUM(total_laid_off)
FROM layoffs_staging2
GROUP BY company
ORDER BY 2 DESC;


-- CONCLUDING DATASET INCLUDES LAYOFFS BETWEEN RESULT OF THE QUERY
SELECT MIN(`date`), MAX(`date`)
FROM layoffs_staging2;
-- ALMOST 3 YEARS BETWEEN MARCH 2020 AND MARCH 2023 AROUND AND AFTERMATH OF COVID


-- CHECKING WHICH INDUSTRIES GOT HIT THE WORST
SELECT industry, SUM(total_laid_off)
FROM layoffs_staging2
GROUP BY industry
ORDER BY 2 DESC;



-- SEEMS LIKE MOST PEOPLE LAID OFF FROM UNITED STATES
-- WHILE WE CAN CONCLUDE US HAD INFLATED EMPLOYMENT AND THEM HANDLING THE WAY THAT THEY DID LED TO THOSE NUMBERS
-- WE CAN ALSO CONCLUDE COLLECTED DATA WAS BIASED TOWARDS US WHICH CAN EXPLAIN THE HUGE DISCREPANCY BETWEEN THE NUMBERS
-- BIAS CAN BE CAUSED BY POLITICAL VIEWS BUT ITS MORE LIKELY THAT US HAD MUCH MORE PUBLICLY AND EASILY AVAILABLE DATA
SELECT country, SUM(total_laid_off)
FROM layoffs_staging2
GROUP BY country
ORDER BY 2 DESC;


-- WHILE THE 2022 LAID OFF NUMBERS ARE LOWER THAN 2023 DATA INCLUDES ONLY ABOUT 3 MONTHS OF 2023
-- WHICH MEANS IT WILL PROBABLY GET MUCH HIGHER
SELECT YEAR(`date`), SUM(total_laid_off)
FROM layoffs_staging2
GROUP BY YEAR(`date`)
ORDER BY 1 DESC;



-- ROLLING TOTAL OF LAYOFFS GROUPED BY MONTH

-- MONTHLY LAYOFFS
SELECT SUBSTRING(`date`, 1, 7) AS `MONTH`, SUM(total_laid_off)
FROM layoffs_staging2
WHERE SUBSTRING(`date`, 1, 7) IS NOT NULL
GROUP BY `MONTH`
ORDER BY 1 ASC;


-- WE ADD MONTHLY LAYOFFS AS A COLUMN TOO TO MAKE DATA MORE EASY TO UNDERSTAND
-- 2021 SEEMS TO BE A GOOD YEAR OCTOBER BEING EXCEPTIONALLY BETTER WITH ONLY 22 PEOPLE LAID OFF
-- ALSO LOOKS LIKE CALM BEFORE STORM AS WE GET TO MORE RECENT TIME-FRAMES
WITH Rolling_Total AS 
(
SELECT SUBSTRING(`date`, 1, 7) AS `MONTH`, SUM(total_laid_off) AS monthly_layoffs
FROM layoffs_staging2
WHERE SUBSTRING(`date`, 1, 7) IS NOT NULL
GROUP BY `MONTH`
ORDER BY 1 ASC
)
SELECT `MONTH`, monthly_layoffs, SUM(monthly_layoffs) OVER(ORDER BY `MONTH`) AS rolling_total
FROM Rolling_Total;


-- COMPANIES' YEARLY LAYOFFS

-- GETTING TOP 5 COMPANIES THAT LAID OFF MOST PEOPLE PER YEAR
-- AS LAY OFF NUMBERS GET REALLY HIGH TOP RANKINGS OR TAKEN OVER FROM LESSER KNOWN COMPANIES BY LARGE COMPANIES 
-- AS LESSER KNOWN COMPANIES GENERALLY DONT HAVE THAT MUCH EMPLOYEES TO LAY OFF TO BEGIN WITH
SELECT company, YEAR(`date`), SUM(total_laid_off)
FROM layoffs_staging2
GROUP BY company, YEAR(`date`)
ORDER BY 3 DESC;  


WITH Company_Year (company, years, yearly_laid_off) AS
(
SELECT company, YEAR(`date`), SUM(total_laid_off)
FROM layoffs_staging2
GROUP BY company, YEAR(`date`)
), Company_Year_Rank as 
(
SELECT * , DENSE_RANK() OVER (PARTITION BY years ORDER BY yearly_laid_off DESC) AS Ranking
FROM Company_Year
-- OMITTING AMBIGUOUS DATA
WHERE years IS NOT NULL AND yearly_laid_off IS NOT NULL
)
SELECT *
FROM Company_Year_Rank
WHERE Ranking <= 5;




